# Generated by Django 4.1.7 on 2023-02-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
    ]
