# Generated by Django 4.1.7 on 2023-02-28 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('placa', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('ano', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('data_compra', models.DateField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('data_aluguel', models.DateField()),
                ('data_entrega', models.DateField()),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.cliente')),
                ('placa_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluguel.carro')),
            ],
        ),
    ]
