# Generated by Django 4.1.7 on 2023-03-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0002_carro_remove_cliente_id_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_aluguel',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='data_entrega',
            field=models.DateField(blank=True),
        ),
    ]
